### ISSUE TITLE
Compile faild

### ISSUE THREAD

**Issue by xclid** [azerothcore/mod-racial-trait-swap#6]
`Error	C1083	Cannot open include file: 'ScriptPCH.h': No such file or directory	modules	D:\azerothcore\modules\mod-racial-trait-swap\src\RacialTraitSwap.cpp	30	`

win2016

https://github.com/azerothcore/azerothcore-wotlk/commit/846487acaa9f4b604af0628bca5685be6815f9ba

**Comment by acidmanifesto** [comment]
Remake cmake. Compiles fine.
